/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/{asset_id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset File */
        get: operations["get_asset_file_api_v1_assets__asset_id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset Permissions
         * @description Permission metadata for an eligible asset.
         *
         *     This is the authoritative answer to "may this asset be traced?": it comes
         *     from the recorded source permission (``allowed_trace``), never from
         *     whether the line art is native or extracted. ``trace_url`` is ``null``
         *     when tracing is not permitted, so a client restoring a saved trace layer
         *     cannot resurrect an asset whose permission was revoked.
         */
        get: operations["get_asset_permissions_api_v1_assets__asset_id__permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/assets/{asset_id}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Asset
         * @description Serve gallery files to the curation UI only, behind reveal controls.
         *
         *     Public ``/api/v1/assets/{id}/...`` routes stay gated on the derived
         *     ``enabled = 1`` flag (the full serving predicate) — they never serve
         *     quarantined/uncertain content, and reveal grants do not apply there.
         *     Here (curation only), *held* records additionally require a deliberate,
         *     unexpired reveal grant; without one the preview fails with
         *     ``reveal_required`` instead of leaking the image.
         */
        get: operations["preview_asset_api_v1_curation_assets__asset_id___kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/assets/{asset_id}/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Crop
         * @description Cut an immutable child derivative from this asset.
         *
         *     The child gets its own identity (deterministic from dataset+item+crop),
         *     its parent's identity links, bounded geometry, **fresh files and
         *     hashes**, and its own processing/review state — it is created
         *     ``unreviewed`` with ``derivatives_current = 0`` (awaiting processing)
         *     and ``enabled = 0``. It can only ever be enabled after its required
         *     processing completes *and* a human accepts it with all serving gates
         *     passing; nothing about the parent's review/SFW/gold state is inherited.
         *     Held (quarantined/uncertain/flagged) parents cannot be cropped — that
         *     would launder held content into a fresh reviewable asset.
         */
        post: operations["create_crop_api_v1_curation_assets__asset_id__crops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/assets/{asset_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Derivative
         * @description Run (or re-run) a derivative's required processing.
         *
         *     Verifies the child's files against their recorded checksums, rebuilds
         *     every measurement from the child's *own* bytes, regenerates the
         *     thumbnail, and — only when all of that succeeds — marks the child's
         *     derivatives current. Index membership (the in-memory serving list) and
         *     the derived ``enabled`` flag are recomputed in the same transaction, and
         *     the response carries the artifact stamp any future embedding must bind
         *     to (per the frozen vector contract, a new derivative has no vectors yet:
         *     ``embedding_status: "missing"``).
         */
        post: operations["process_derivative_api_v1_curation_assets__asset_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/candidates/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidate
         * @description Stable retrieval of one candidate by id, whatever its review state.
         *
         *     This is the read path for Previous (re-fetch the *actual* previous
         *     candidate — live metadata, not a stale copy) and for conflict
         *     reconciliation after a 409.
         */
        get: operations["get_candidate_api_v1_curation_candidates__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Label */
        post: operations["write_label_api_v1_curation_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Candidate */
        get: operations["next_candidate_api_v1_curation_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_v1_curation_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Quarantine
         * @description The SFW adjudication backlog: held records, **metadata only**.
         *
         *     Quarantined (any reason), screened unsafe/unsure, or human-flagged
         *     records. No image bytes and no preview URLs until a deliberate reveal.
         */
        get: operations["list_quarantine_api_v1_curation_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/quarantine/{asset_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Quarantined
         * @description Issue a deliberate, expiring reveal grant for one held record.
         *
         *     The grant is recorded (who revealed what, when, until when) and is the
         *     *only* way the curation preview route will serve held content. It never
         *     applies to the public asset routes, and it changes nothing about the
         *     asset itself — review state, version, and eligibility are untouched.
         */
        post: operations["reveal_quarantined_api_v1_curation_quarantine__asset_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/queue/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Candidate
         * @description Advance the session past an asset without a label.
         *
         *     The asset is excluded from *this session's* queue (it is not mutated:
         *     its review state, version, and eligibility are untouched) and the cursor
         *     moves to it, so the next serve is a different item.
         */
        post: operations["skip_candidate_api_v1_curation_queue_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/sfw/{asset_id}/adjudication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjudicate Sfw
         * @description Record an explicit human SFW adjudication for a held/uncertain record.
         *
         *     Effects (one transaction, atomic conditional on ``expected_label_version``):
         *
         *     * ``safe`` — the human decision is mirrored onto the asset and a
         *       quarantined record returns to ``unreviewed`` so it can be reviewed on
         *       its merits through the normal queue. Serving still requires every
         *       other gate (permission, accepted review with quality, no blockers).
         *     * ``unsafe`` — the record is quarantined and human-flagged; it leaves
         *       every serving surface until a future adjudication says otherwise.
         *       The public asset routes were already closed to it and stay closed.
         *
         *     Both outcomes are append-only audit history in ``sfw_adjudications``.
         */
        post: operations["adjudicate_sfw_api_v1_curation_sfw__asset_id__adjudication_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curation/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Snapshot
         * @description Write an immutable **full** snapshot of the current curation state.
         *
         *     Frozen semantics: the snapshot captures the *latest* keep-or-reject
         *     label per asset — rejected assets included — from a **consistent
         *     database view**. The whole export (label read, lineage read, file
         *     publication, registry insert, and the exact linking of the exported
         *     label rows to the snapshot) runs inside one ``BEGIN IMMEDIATE``
         *     transaction, so a concurrent label write or a concurrent export can
         *     never interleave: writers serialize, the second export chains to the
         *     first via ``previous_snapshot_id``, and neither file can overwrite the
         *     other. Every export is a new file; snapshots are never edited and never
         *     incremental, and the append-only ``curation_labels`` audit history stays
         *     complete in the database. The published bytes' SHA-256 is recorded on
         *     the registry row so the export stays verifiable after later edits.
         */
        post: operations["export_snapshot_api_v1_curation_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Event
         * @description Record an interaction. Timestamp, style, and namespace are server-side.
         */
        post: operations["record_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pins
         * @description Pins for this API's gallery namespace, revalidated on every read.
         */
        get: operations["get_pins_api_v1_pins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pins/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Pin Asset
         * @description Pin an asset. Idempotent: re-pinning keeps the original pin time.
         */
        put: operations["pin_asset_api_v1_pins__asset_id__put"];
        post?: never;
        /**
         * Unpin Asset
         * @description Unpin an asset. Idempotent, and never a negative learning signal.
         *
         *     Unpinning an asset that is not pinned (or no longer exists) succeeds: the
         *     caller's intent — "this must not be pinned" — is already true.
         */
        delete: operations["unpin_asset_api_v1_pins__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_v1_preferences_get"];
        /** Update Preferences */
        put: operations["update_preferences_api_v1_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllowedUses
         * @description What the asset may be used for. Three independent grants, all opt-in.
         *
         *     A use is only ``True`` when the permission basis justifies it (or a
         *     recorded human permission decision does). Anything unknown stays ``False``:
         *     unknown permission must not imply permission.
         */
        AllowedUses: {
            /**
             * Display
             * @default false
             */
            display: boolean;
            /**
             * Trace
             * @default false
             */
            trace: boolean;
            /**
             * Training
             * @default false
             */
            training: boolean;
        };
        /**
         * AssetPermissions
         * @description Permission metadata a client needs before *using* an asset.
         *
         *     ``trace_url`` is populated only when tracing is permitted, so a client
         *     that restores a saved trace layer cannot resurrect an asset whose trace
         *     permission was revoked.
         */
        AssetPermissions: {
            /** Allowed Display */
            allowed_display: boolean;
            /** Allowed Trace */
            allowed_trace: boolean;
            /** Asset Id */
            asset_id: string;
            /** Asset Url */
            asset_url: string;
            /** Attribution */
            attribution?: string | null;
            /**
             * Attribution Required
             * @default false
             */
            attribution_required: boolean;
            origin: components["schemas"]["LineArtOrigin"];
            permission_basis: components["schemas"]["PermissionBasis"];
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Trace Url */
            trace_url?: string | null;
        };
        /** Body_search_api_v1_search_post */
        Body_search_api_v1_search_post: {
            /** Canvas Height */
            canvas_height: number;
            /** Canvas Width */
            canvas_width: number;
            /** Image */
            image: string;
            /** Point Count */
            point_count: number;
            /** Revision */
            revision: number;
            selected_style?: components["schemas"]["StyleSelection"] | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Stroke Count */
            stroke_count: number;
            /** Strokes */
            strokes?: string | null;
            /** Text Hint */
            text_hint?: string | null;
        };
        /**
         * CropBox
         * @description Crop coordinates in source-image pixel space (inclusive-exclusive).
         */
        CropBox: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * CropRequest
         * @description Body of ``POST /curation/assets/{asset_id}/crops``.
         *
         *     The crop is cut from the parent's *current, verified* line art; the child
         *     is created pending its own processing and review.
         */
        CropRequest: {
            crop: components["schemas"]["CropBox"];
            /** Expected Label Version */
            expected_label_version: number;
            /** Note */
            note?: string | null;
            /** Reviewer */
            reviewer?: string | null;
        };
        /** CropResponse */
        CropResponse: {
            /** Asset Id */
            asset_id: string;
            /** Created */
            created: boolean;
            crop: components["schemas"]["CropBox"];
            /** Derivatives Current */
            derivatives_current: boolean;
            /** Height */
            height: number;
            /** Label Version */
            label_version: number;
            /** Parent Asset Id */
            parent_asset_id: string;
            /**
             * Processing State
             * @enum {string}
             */
            processing_state: "pending" | "complete" | "failed";
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            /** Width */
            width: number;
        };
        /**
         * CurationBlocker
         * @description A named defect that blocks specific uses regardless of review state.
         *
         *     Blockers are not review states; they are assertions about the asset that
         *     outlive individual decisions. While any blocker is present the asset is
         *     neither servable nor trainable (see ``is_servable`` / ``is_trainable`` in
         *     :mod:`linescout_ml.manifest`). The curation API refuses a ``keep`` decision
         *     that carries blockers — blockers force ``reject`` or ``quarantine``.
         *
         *     Adding a new blocker kind is a schema change: extend this enum, bump the
         *     manifest schema version, and migrate the ``blockers_json`` columns.
         * @enum {string}
         */
        CurationBlocker: "anatomy" | "extraction";
        /**
         * CurationCandidate
         * @description One candidate asset for review (the v2 wire shape).
         */
        CurationCandidate: {
            allowed_uses: components["schemas"]["AllowedUses"];
            /** Artist Id */
            artist_id?: string | null;
            /** Asset Id */
            asset_id: string;
            /** Blockers */
            blockers?: components["schemas"]["CurationBlocker"][];
            crop?: components["schemas"]["CropBox"] | null;
            /** Derivative Processing State */
            derivative_processing_state?: ("pending" | "complete" | "failed") | null;
            /**
             * Gallery Member
             * @default true
             */
            gallery_member: boolean;
            /**
             * Gold Member
             * @default false
             */
            gold_member: boolean;
            /** Height */
            height: number;
            /** Label Version */
            label_version: number;
            /** Leakage Group Id */
            leakage_group_id?: string | null;
            learning_split: components["schemas"]["LearningSplit"];
            /** Line Art Url */
            line_art_url: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "native_line_art" | "extracted_line_art";
            /** Parent Asset Id */
            parent_asset_id?: string | null;
            permissions: components["schemas"]["Permissions"];
            /** Person Count */
            person_count?: number | null;
            /**
             * Person Count Approximate
             * @default false
             */
            person_count_approximate: boolean;
            primary_scope: components["schemas"]["ScopeLabel"];
            primary_style: components["schemas"]["PrimaryStyle"];
            /** Quality Score */
            quality_score: number;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            /** Secondary Scopes */
            secondary_scopes?: components["schemas"]["ScopeLabel"][];
            sfw_human?: components["schemas"]["SfwHumanDecision"] | null;
            sfw_screening?: components["schemas"]["SfwScreening"] | null;
            /** Source Work Id */
            source_work_id: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Width */
            width: number;
        };
        /**
         * CurationProgress
         * @description Overall review progress plus style/scope breakdowns.
         */
        CurationProgress: {
            /** Accepted */
            accepted: number;
            /** By Scope */
            by_scope: {
                [key: string]: components["schemas"]["ScopeBreakdown"];
            };
            /** By Style */
            by_style: {
                [key: string]: components["schemas"]["StyleBreakdown"];
            };
            /** Quarantined */
            quarantined: number;
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
            /**
             * Target
             * @default 2000
             */
            target: number;
        };
        /**
         * Degradation
         * @description One structured way this response is degraded relative to full quality.
         *
         *     ``degradations`` on the response is the canonical, machine-readable view;
         *     the top-level ``warning`` string is a convenience join kept for older
         *     clients and may be removed in a future contract version.
         *
         *     The kinds split by what is degraded: ``fixture_mode``/``cpu_fallback``/
         *     ``branch_disabled``/``gallery_empty`` describe the *server*, while
         *     ``blank_raster``/``vector_absent``/``vector_sparse`` describe this
         *     *query's input*. A client that only wants to know whether the stroke
         *     branch contributed filters on the input kinds; ``branch_disabled`` means
         *     the branch is off for every query, not for this one.
         */
        Degradation: {
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fixture_mode" | "cpu_fallback" | "branch_disabled" | "gallery_empty" | "blank_raster" | "vector_absent" | "vector_sparse";
        };
        /**
         * DerivativeArtifactStamp
         * @description Binds embeddings/index entries to the exact derivative bytes.
         *
         *     Matches the frozen vector contract (``ml/linescout_ml/embeddings.py``):
         *     an embedding entry is only ``available`` when its recorded stamp equals
         *     the asset's current stamp. A freshly processed derivative has no vectors
         *     yet, so its embedding status is ``missing`` until the index build.
         */
        DerivativeArtifactStamp: {
            /** Line Art Checksum */
            line_art_checksum: string;
            /** Processing Revision */
            processing_revision: number;
        };
        /**
         * DerivativeMeasurements
         * @description Measurements rebuilt from the derivative's own bytes.
         */
        DerivativeMeasurements: {
            /** Background Coverage */
            background_coverage: number;
            /** Height */
            height: number;
            /** Ink Coverage */
            ink_coverage: number;
            /** Phash */
            phash: string;
            /** Quality Score */
            quality_score: number;
            /** Text Coverage */
            text_coverage: number;
            /** Width */
            width: number;
        };
        /** DerivativeProcessResponse */
        DerivativeProcessResponse: {
            artifact: components["schemas"]["DerivativeArtifactStamp"];
            /** Asset Id */
            asset_id: string;
            /** Attempts */
            attempts: number;
            /** Derivatives Current */
            derivatives_current: boolean;
            /**
             * Embedding Status
             * @default missing
             * @constant
             */
            embedding_status: "missing";
            /** Enabled */
            enabled: boolean;
            /** Label Version */
            label_version: number;
            measurements?: components["schemas"]["DerivativeMeasurements"] | null;
            /** Parent Asset Id */
            parent_asset_id: string;
            /**
             * Processing State
             * @enum {string}
             */
            processing_state: "pending" | "complete" | "failed";
            /** Serving Blockers */
            serving_blockers?: string[];
        };
        /**
         * ErrorDetail
         * @description One structured error.
         *
         *     ``code`` is a stable, machine-readable slug (never a filename or path).
         *     ``field`` names the offending request field when one field is at fault.
         *     ``details`` is optional, code-specific structured data (e.g. byte limits
         *     for ``image_too_large``); it must never contain absolute filesystem paths,
         *     user content, or secrets.
         */
        ErrorDetail: {
            /**
             * Code
             * @description Stable machine-readable error code, e.g. image_too_large.
             */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description Structured error envelope required on every failure path.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Retryable */
            retryable: boolean;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** EventRequest */
        EventRequest: {
            /** Asset Id */
            asset_id: string;
            event: components["schemas"]["InteractionEvent"];
            /**
             * Event Uuid
             * Format: uuid
             * @description Client-generated UUID identifying this interaction attempt (idempotency key).
             */
            event_uuid: string;
            /** Query Revision */
            query_revision: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * @deprecated
             * @description Deprecated and ignored. Style is derived server-side from the gallery row, so this field is not part of the request's authoritative payload and never affects idempotency. It is accepted only so older clients keep working.
             */
            style?: components["schemas"]["PrimaryStyle"] | null;
        };
        /** EventResponse */
        EventResponse: {
            /** Created At */
            created_at: string;
            /**
             * Event Uuid
             * Format: uuid
             */
            event_uuid: string;
            /** Id */
            id: number;
            /**
             * Recorded
             * @default true
             */
            recorded: boolean;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
        };
        /**
         * GalleryKind
         * @description Namespace an interaction or pin belongs to.
         *
         *     Stamped server-side from the API's own mode: fixture-gallery state can
         *     never mix with live-gallery state.
         * @enum {string}
         */
        GalleryKind: "fixture" | "live";
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Cuda Available */
            cuda_available: boolean;
            /** Curation Enabled */
            curation_enabled: boolean;
            /** Dataset Version */
            dataset_version: string | null;
            /**
             * Device
             * @enum {string}
             */
            device: "cuda" | "cpu";
            /**
             * Disabled Branches
             * @description Optional retrieval branches disabled this session, e.g. pose.
             */
            disabled_branches: string[];
            /** Fixture Mode */
            fixture_mode: boolean;
            /** Gallery Size */
            gallery_size: number;
            /** Gpu Name */
            gpu_name: string | null;
            /** Index Version */
            index_version: string | null;
            /** Models */
            models: components["schemas"]["ModelVersion"][];
            /** Preprocessing Version */
            preprocessing_version: string;
            /** Ready */
            ready: boolean;
            /** Schema Version */
            schema_version: number;
            /** Torch Version */
            torch_version: string | null;
            /** Vram Total Mb */
            vram_total_mb: number | null;
            /**
             * Warmup
             * @enum {string}
             */
            warmup: "pending" | "complete" | "skipped";
            /** Warnings */
            warnings: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InteractionEvent
         * @enum {string}
         */
        InteractionEvent: "open" | "pin" | "unpin" | "trace";
        /**
         * LabelRequest
         * @description Body of ``POST /curation/labels``.
         */
        LabelRequest: {
            /** Asset Id */
            asset_id: string;
            /** Blockers */
            blockers?: components["schemas"]["CurationBlocker"][];
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "reject";
            /** Expected Label Version */
            expected_label_version: number;
            expected_review_state: components["schemas"]["ReviewState"];
            /** Note */
            note?: string | null;
            primary_scope?: components["schemas"]["ScopeLabel"] | null;
            primary_style?: components["schemas"]["PrimaryStyle"] | null;
            /** Quality */
            quality?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Secondary Scopes */
            secondary_scopes?: components["schemas"]["ScopeLabel"][] | null;
            /** Session Id */
            session_id?: string | null;
            /** Sfw Safe */
            sfw_safe?: boolean | null;
        };
        /** LabelResponse */
        LabelResponse: {
            /** Asset Id */
            asset_id: string;
            /** Blockers */
            blockers?: components["schemas"]["CurationBlocker"][];
            /** Created At */
            created_at: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "reject";
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Label Version */
            label_version: number;
            /** Review Quality */
            review_quality: number | null;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            /** Serving Blockers */
            serving_blockers?: string[];
            /** Sfw Human Approved */
            sfw_human_approved: boolean | null;
        };
        /**
         * LearningSplit
         * @description Learning assignment for an asset. Gallery/gold membership is separate.
         *
         *     ``none`` means *no training assignment*: the asset is excluded from every
         *     learning population. It is not a conflict in the one-group-one-split rule
         *     (only two different assigned splits on the same work or leakage group
         *     are). The default derivation policy keeps 70/15/15 over assigned works.
         * @enum {string}
         */
        LearningSplit: "train" | "validation" | "test" | "none";
        /**
         * LineArtOrigin
         * @description Whether the visible reference is native line art or machine-extracted.
         * @enum {string}
         */
        LineArtOrigin: "native_line_art" | "extracted_line_art";
        /** ModelVersion */
        ModelVersion: {
            /** Device */
            device?: string | null;
            /** Loaded */
            loaded: boolean;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * PermissionBasis
         * @description Why the asset's allowed uses may be claimed.
         *
         *     * ``license_terms``    — the recorded licence's terms grant the use.
         *     * ``public_domain``    — no rights reserved (verified dedication).
         *     * ``explicit_consent`` — the artist/source gave recorded permission.
         *     * ``first_party``      — content produced by this project itself.
         *     * ``unknown``          — the default. Grants *nothing*: unknown permission
         *       must not imply permission.
         * @enum {string}
         */
        PermissionBasis: "license_terms" | "public_domain" | "explicit_consent" | "first_party" | "unknown";
        /**
         * Permissions
         * @description Permission provenance for one asset.
         *
         *     ``license_id`` has no default — provenance is the point of the manifest,
         *     and a silent default would let an unverified licence claim ship. ``basis``
         *     defaults to ``unknown``, which grants no uses at all.
         */
        Permissions: {
            /** Attribution */
            attribution?: string | null;
            /**
             * Attribution Required
             * @default false
             */
            attribution_required: boolean;
            /** @default unknown */
            basis: components["schemas"]["PermissionBasis"];
            /** License Id */
            license_id: string;
            /** Permission Url */
            permission_url?: string | null;
        };
        /**
         * PinnedAsset
         * @description A durably pinned reference, projected against the *current* gallery.
         *
         *     The projection is recomputed on every read, so a permission or eligibility
         *     change is reflected immediately: ``trace_allowed`` is the asset's stored
         *     trace permission (never inferred from ``origin``), and an asset that lost
         *     display eligibility does not appear here at all.
         */
        PinnedAsset: {
            /** Asset Id */
            asset_id: string;
            /** Asset Url */
            asset_url: string;
            origin: components["schemas"]["LineArtOrigin"];
            /** Person Count */
            person_count?: number | null;
            /**
             * Person Count Approximate
             * @default false
             */
            person_count_approximate: boolean;
            /** Pinned At */
            pinned_at: string;
            primary_scope: components["schemas"]["ScopeLabel"];
            /** Quality */
            quality: number;
            /** Scopes */
            scopes: components["schemas"]["ScopeLabel"][];
            /** Secondary Scopes */
            secondary_scopes?: components["schemas"]["ScopeLabel"][];
            style: components["schemas"]["PrimaryStyle"];
            /** Thumbnail Url */
            thumbnail_url: string;
            /**
             * Trace Allowed
             * @description Stored per-asset trace permission; never derived from origin.
             */
            trace_allowed: boolean;
        };
        /** PinsResponse */
        PinsResponse: {
            gallery_kind: components["schemas"]["GalleryKind"];
            /** Pins */
            pins: components["schemas"]["PinnedAsset"][];
            /**
             * Revoked
             * @description Pins removed by this read because revalidation found the asset ineligible (permission revoked, review changed, derivatives stale, or asset gone).
             */
            revoked?: components["schemas"]["RevokedPin"][];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /** Affinities */
            affinities: components["schemas"]["StyleAffinity"][];
            /** Learning Enabled */
            learning_enabled: boolean;
            /**
             * Row Order
             * @description Style-row order after Best Match: explicit style first, then learned affinity, then the fixed default order as tie-breaker.
             */
            row_order: components["schemas"]["PrimaryStyle"][];
            selected_style: components["schemas"]["PrimaryStyle"] | null;
        };
        /**
         * PreferencesUpdate
         * @description Partial update; omitted fields are left unchanged.
         */
        PreferencesUpdate: {
            /**
             * Clear Selected Style
             * @description Clear the explicit style.
             * @default false
             */
            clear_selected_style: boolean;
            /** Learning Enabled */
            learning_enabled?: boolean | null;
            /**
             * Reset Affinities
             * @description Forget learned affinities. Pins are durable application state and are never cleared by a reset.
             * @default false
             */
            reset_affinities: boolean;
            /** @description Explicitly select a style. Ignored unless provided. */
            selected_style?: components["schemas"]["PrimaryStyle"] | null;
        };
        /**
         * PrimaryStyle
         * @description Exactly one primary style per asset. Also the five reference-panel rows.
         * @enum {string}
         */
        PrimaryStyle: "manga_anime" | "western_ink" | "realistic_academic" | "cartoon" | "gesture_sketch";
        /**
         * QuarantineCandidate
         * @description One held record in the SFW adjudication backlog (metadata only).
         *
         *     Image URLs stay ``None`` until a deliberate reveal grant exists; the
         *     preview route enforces the grant independently, so the URLs are never a
         *     bypass.
         */
        QuarantineCandidate: {
            /** Asset Id */
            asset_id: string;
            /** Blockers */
            blockers?: components["schemas"]["CurationBlocker"][];
            /** Derivative Processing State */
            derivative_processing_state?: ("pending" | "complete" | "failed") | null;
            /** Height */
            height: number;
            /** Label Version */
            label_version: number;
            /** Line Art Url */
            line_art_url?: string | null;
            /** Parent Asset Id */
            parent_asset_id?: string | null;
            primary_scope: components["schemas"]["ScopeLabel"];
            primary_style: components["schemas"]["PrimaryStyle"];
            /** Quality Score */
            quality_score: number;
            /** Reveal Expires At */
            reveal_expires_at?: string | null;
            /**
             * Revealed
             * @default false
             */
            revealed: boolean;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            sfw_human?: components["schemas"]["SfwHumanDecision"] | null;
            sfw_screening?: components["schemas"]["SfwScreening"] | null;
            /** Source Work Id */
            source_work_id: string;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Width */
            width: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Ready
             * @default true
             * @constant
             */
            ready: true;
        };
        /**
         * RevealRequest
         * @description Body of ``POST /curation/quarantine/{asset_id}/reveal``.
         */
        RevealRequest: {
            /** Reviewer */
            reviewer?: string | null;
        };
        /**
         * ReviewState
         * @description Human curation state for an asset (definitions are part of the contract).
         *
         *     * ``unreviewed`` — no human decision recorded. Not servable, not trainable.
         *     * ``accepted``   — a human approved the asset's labels. Servable iff the
         *       other gates pass (display permission, gallery membership, human SFW
         *       approval, no blockers); trainable iff training permission and split allow.
         *     * ``rejected``   — terminal human verdict that the asset is unsuitable.
         *       Never served, never trained on as a positive example; retained for audit
         *       and (only where training use is permitted) as a negative example for
         *       quality models.
         *     * ``quarantined``— reversible hold pending investigation (SFW concern,
         *       provenance concern, extraction rework). All uses blocked while held.
         * @enum {string}
         */
        ReviewState: "unreviewed" | "accepted" | "rejected" | "quarantined";
        /**
         * RevokedPin
         * @description A pin dropped because its asset is no longer eligible to be shown.
         */
        RevokedPin: {
            /** Asset Id */
            asset_id: string;
            /**
             * Reasons
             * @description Stable machine-readable serving blockers, e.g. display_not_permitted.
             */
            reasons: string[];
        };
        /**
         * ScopeBreakdown
         * @description Reviewed/accepted/rejected counts for a single scope bucket.
         */
        ScopeBreakdown: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
        };
        /**
         * ScopeLabel
         * @description What part of a character (or how many characters) an image depicts.
         *
         *     An asset carries exactly one ``primary_scope`` plus any number of
         *     ``secondary_scopes``; queries return one probability per label plus
         *     ``unknown``.
         *
         *     ``eyebrow`` and ``mouth`` are retained as first-class detail scopes, and
         *     ``person_count`` stays nullable on the record (null = not applicable or
         *     not assessed).
         * @enum {string}
         */
        ScopeLabel: "eye" | "eyebrow" | "mouth" | "face_head" | "hair" | "hand" | "foot" | "upper_body_clothing" | "full_body" | "multi_character" | "unknown";
        /** ScopePrediction */
        ScopePrediction: {
            /** Confidence */
            confidence: number;
            label: components["schemas"]["ScopeLabel"];
        };
        /** SearchGroup */
        SearchGroup: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "best_match" | "style" | "provisional_scope";
            /** Results */
            results: components["schemas"]["SearchResult"][];
            scope?: components["schemas"]["ScopeLabel"] | null;
            style?: components["schemas"]["PrimaryStyle"] | null;
            /** Title */
            title: string;
        };
        /**
         * SearchMode
         * @enum {string}
         */
        SearchMode: "insufficient" | "provisional" | "confident";
        /** SearchResponse */
        SearchResponse: {
            /** Api Version */
            api_version: string;
            /** Canvas Height */
            canvas_height: number;
            /** Canvas Width */
            canvas_width: number;
            /** Counts Approximate */
            counts_approximate: boolean;
            /** Dataset Version */
            dataset_version?: string | null;
            /** Degradations */
            degradations?: components["schemas"]["Degradation"][];
            /** Groups */
            groups: components["schemas"]["SearchGroup"][];
            /** Index Version */
            index_version?: string | null;
            mode: components["schemas"]["SearchMode"];
            /** Preprocessing Version */
            preprocessing_version: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Revision
             * @description Echoes the request revision unchanged.
             */
            revision: number;
            /**
             * Schema Version
             * @description Payload contract version; bump on any breaking response change.
             * @default 2
             * @constant
             */
            schema_version: 2;
            /** Scope Predictions */
            scope_predictions: components["schemas"]["ScopePrediction"][];
            stroke_status: components["schemas"]["StrokeStatus"];
            timing: components["schemas"]["SearchTiming"];
            /** Warning */
            warning?: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Asset Id */
            asset_id: string;
            /**
             * Asset Url
             * @description Trace-compatible full asset URL.
             */
            asset_url: string;
            origin: components["schemas"]["LineArtOrigin"];
            /** Person Count */
            person_count?: number | null;
            /**
             * Person Count Approximate
             * @default false
             */
            person_count_approximate: boolean;
            primary_scope: components["schemas"]["ScopeLabel"];
            /** Quality */
            quality: number;
            /**
             * Relevance
             * @description Calibrated relevance probability.
             */
            relevance: number;
            /** Scopes */
            scopes: components["schemas"]["ScopeLabel"][];
            /** Secondary Scopes */
            secondary_scopes?: components["schemas"]["ScopeLabel"][];
            style: components["schemas"]["PrimaryStyle"];
            /** Thumbnail Url */
            thumbnail_url: string;
            /**
             * Trace Allowed
             * @description Whether this asset may be placed on the trace layer. Stored per-asset permission (v2); never derived from origin on the wire.
             */
            trace_allowed: boolean;
        };
        /** SearchTiming */
        SearchTiming: {
            /** Embedding Ms */
            embedding_ms: number;
            /** Preprocessing Ms */
            preprocessing_ms: number;
            /** Reranking Ms */
            reranking_ms: number;
            /** Retrieval Ms */
            retrieval_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /**
         * SfwAdjudicationRequest
         * @description Body of ``POST /curation/sfw/{asset_id}/adjudication``.
         */
        SfwAdjudicationRequest: {
            /** Expected Label Version */
            expected_label_version: number;
            /** Note */
            note?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Safe */
            safe: boolean;
            /** Session Id */
            session_id?: string | null;
        };
        /** SfwAdjudicationResponse */
        SfwAdjudicationResponse: {
            /** Asset Id */
            asset_id: string;
            /** Created At */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Label Version */
            label_version: number;
            /**
             * Review State
             * @enum {string}
             */
            review_state: "unreviewed" | "accepted" | "rejected" | "quarantined";
            /** Safe */
            safe: boolean;
            /** Serving Blockers */
            serving_blockers?: string[];
            sfw_human: components["schemas"]["SfwHumanDecision"];
        };
        /**
         * SfwHumanDecision
         * @description A human SFW decision. The only thing that can gate display.
         */
        SfwHumanDecision: {
            /** Decided At */
            decided_at?: string | null;
            /**
             * Reviewer
             * @default local
             */
            reviewer: string;
            /** Safe */
            safe: boolean;
        };
        /**
         * SfwScreening
         * @description An automated (machine) SFW screen. Never a substitute for approval.
         *
         *     ``None`` on the record means no screen was ever run. A screen result is
         *     tri-state: ``unsure`` is a concern to resolve, not a pass.
         */
        SfwScreening: {
            /** Confidence */
            confidence?: number | null;
            /** @default none */
            method: components["schemas"]["SfwScreeningMethod"];
            verdict: components["schemas"]["SfwVerdict"];
        };
        /**
         * SfwScreeningMethod
         * @description How an automated SFW screen was produced.
         *
         *     ``manual`` is deliberately absent: a human SFW decision is recorded
         *     separately on the manifest record (``sfw_human``), never as a screening
         *     method.
         * @enum {string}
         */
        SfwScreeningMethod: "none" | "source_rating" | "opennsfw2" | "source_rating+opennsfw2";
        /**
         * SfwVerdict
         * @description Tri-state result of an automated SFW screen.
         *
         *     ``unsure`` is distinct from ``unsafe``: borderline confidence is a concern
         *     to resolve, not a condemnation. Both ``unsafe`` and ``unsure`` keep an
         *     asset out of the unreviewed queue at ingestion (quarantined instead), and
         *     neither ever substitutes for human approval.
         * @enum {string}
         */
        SfwVerdict: "safe" | "unsafe" | "unsure";
        /**
         * SkipRequest
         * @description Body of ``POST /curation/queue/skip``.
         */
        SkipRequest: {
            /** Asset Id */
            asset_id: string;
            /** Session Id */
            session_id: string;
        };
        /** SkipResponse */
        SkipResponse: {
            /** Cursor Asset Id */
            cursor_asset_id: string;
            /** Excluded Asset Id */
            excluded_asset_id: string;
            /** Remaining */
            remaining: number;
            /** Session Id */
            session_id: string;
        };
        /**
         * SnapshotResponse
         * @description Body of ``POST /curation/snapshots``.
         */
        SnapshotResponse: {
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string;
            /** Label Count */
            label_count: number;
            /** Path */
            path: string;
            /** Previous Snapshot Id */
            previous_snapshot_id: string | null;
            /** Snapshot Id */
            snapshot_id: string;
            /** Style Breakdown */
            style_breakdown: {
                [key: string]: number;
            };
        };
        /** Stroke */
        Stroke: {
            /**
             * Pointer
             * @enum {string}
             */
            pointer: "pen" | "mouse" | "touch";
            /** Points */
            points: components["schemas"]["StrokePoint"][];
            /**
             * Tool
             * @enum {string}
             */
            tool: "pressure" | "monoline" | "eraser";
        };
        /**
         * StrokePoint
         * @description One sampled pointer position inside the gzipped ``strokes`` field.
         */
        StrokePoint: {
            /**
             * P
             * @description Normalized pressure.
             */
            p: number;
            /**
             * T
             * @description Milliseconds since the stroke sequence started.
             */
            t: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** StrokeSequence */
        StrokeSequence: {
            /** Canvas Height */
            canvas_height: number;
            /** Canvas Width */
            canvas_width: number;
            /** Strokes */
            strokes: components["schemas"]["Stroke"][];
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
        };
        /**
         * StrokeStatus
         * @description Whether a vector ``strokes`` payload accompanied the snapshot.
         *
         *     ``absent`` means the query was raster-only (e.g. an imported image), so the
         *     reported ``stroke_count``/``point_count`` are client estimates over the
         *     snapshot with no vector ground truth to verify them against.
         * @enum {string}
         */
        StrokeStatus: "present" | "absent";
        /** StyleAffinity */
        StyleAffinity: {
            /**
             * Affinity
             * @description Laplace-smoothed, decayed share.
             */
            affinity: number;
            style: components["schemas"]["PrimaryStyle"];
        };
        /**
         * StyleBreakdown
         * @description Reviewed/accepted/rejected counts for a single style family.
         */
        StyleBreakdown: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Remaining */
            remaining: number;
            /** Reviewed */
            reviewed: number;
        };
        /**
         * StyleSelection
         * @description ``selected_style`` multipart value: a style enum or ``all``.
         * @enum {string}
         */
        StyleSelection: "all" | "manga_anime" | "western_ink" | "realistic_academic" | "cartoon" | "gesture_sketch";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_asset_file_api_v1_assets__asset_id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_permissions_api_v1_assets__asset_id__permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetPermissions"];
                };
            };
            /** @description Unknown or ineligible asset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_asset_api_v1_curation_assets__asset_id___kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crop_api_v1_curation_assets__asset_id__crops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_derivative_api_v1_curation_assets__asset_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivativeProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_v1_curation_candidates__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_label_api_v1_curation_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_candidate_api_v1_curation_next_get: {
        parameters: {
            query?: {
                /** @description Filter by scope bucket */
                scope?: components["schemas"]["ScopeLabel"] | null;
                /** @description Review session id: enables the cursor/skip queue semantics */
                session_id?: string | null;
                /** @description Filter by primary style */
                style?: components["schemas"]["PrimaryStyle"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_v1_curation_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurationProgress"];
                };
            };
        };
    };
    list_quarantine_api_v1_curation_quarantine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineCandidate"][];
                };
            };
        };
    };
    reveal_quarantined_api_v1_curation_quarantine__asset_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_candidate_api_v1_curation_queue_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjudicate_sfw_api_v1_curation_sfw__asset_id__adjudication_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SfwAdjudicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SfwAdjudicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_api_v1_curation_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    record_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Tracing this asset is not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown or ineligible asset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description event_uuid reused with a different payload */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_pins_api_v1_pins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinsResponse"];
                };
            };
        };
    };
    pin_asset_api_v1_pins__asset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinsResponse"];
                };
            };
            /** @description Unknown or ineligible asset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpin_asset_api_v1_pins__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_v1_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    update_preferences_api_v1_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Model or gallery is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_search_api_v1_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Malformed image or strokes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Body too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid field */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Model or gallery is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const cropResponseProcessing_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CropResponse"]["processing_state"]> = ["pending", "complete", "failed"];
export const cropResponseReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CropResponse"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const curationBlockerValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationBlocker"]> = ["anatomy", "extraction"];
export const curationCandidateDerivative_processing_stateAnyOf0Values: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationCandidate"]["derivative_processing_state"]> = ["pending", "complete", "failed"];
export const curationCandidateOriginValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationCandidate"]["origin"]> = ["native_line_art", "extracted_line_art"];
export const curationCandidateReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CurationCandidate"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const degradationKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Degradation"]["kind"]> = ["fixture_mode", "cpu_fallback", "branch_disabled", "gallery_empty", "blank_raster", "vector_absent", "vector_sparse"];
export const derivativeProcessResponseProcessing_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DerivativeProcessResponse"]["processing_state"]> = ["pending", "complete", "failed"];
export const galleryKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["GalleryKind"]> = ["fixture", "live"];
export const healthResponseDeviceValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["device"]> = ["cuda", "cpu"];
export const healthResponseWarmupValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["warmup"]> = ["pending", "complete", "skipped"];
export const interactionEventValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["InteractionEvent"]> = ["open", "pin", "unpin", "trace"];
export const labelRequestDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelRequest"]["decision"]> = ["keep", "reject"];
export const labelResponseDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelResponse"]["decision"]> = ["keep", "reject"];
export const labelResponseReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LabelResponse"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const learningSplitValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LearningSplit"]> = ["train", "validation", "test", "none"];
export const lineArtOriginValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LineArtOrigin"]> = ["native_line_art", "extracted_line_art"];
export const permissionBasisValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PermissionBasis"]> = ["license_terms", "public_domain", "explicit_consent", "first_party", "unknown"];
export const primaryStyleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PrimaryStyle"]> = ["manga_anime", "western_ink", "realistic_academic", "cartoon", "gesture_sketch"];
export const quarantineCandidateDerivative_processing_stateAnyOf0Values: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["QuarantineCandidate"]["derivative_processing_state"]> = ["pending", "complete", "failed"];
export const quarantineCandidateReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["QuarantineCandidate"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const reviewStateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReviewState"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const scopeLabelValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ScopeLabel"]> = ["eye", "eyebrow", "mouth", "face_head", "hair", "hand", "foot", "upper_body_clothing", "full_body", "multi_character", "unknown"];
export const searchGroupKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchGroup"]["kind"]> = ["best_match", "style", "provisional_scope"];
export const searchModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchMode"]> = ["insufficient", "provisional", "confident"];
export const sfwAdjudicationResponseReview_stateValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SfwAdjudicationResponse"]["review_state"]> = ["unreviewed", "accepted", "rejected", "quarantined"];
export const sfwScreeningMethodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SfwScreeningMethod"]> = ["none", "source_rating", "opennsfw2", "source_rating+opennsfw2"];
export const sfwVerdictValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SfwVerdict"]> = ["safe", "unsafe", "unsure"];
export const strokePointerValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Stroke"]["pointer"]> = ["pen", "mouse", "touch"];
export const strokeToolValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Stroke"]["tool"]> = ["pressure", "monoline", "eraser"];
export const strokeStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StrokeStatus"]> = ["present", "absent"];
export const styleSelectionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StyleSelection"]> = ["all", "manga_anime", "western_ink", "realistic_academic", "cartoon", "gesture_sketch"];
